export const RANDOM_PHOTO_LOADING = 'RANDOM_PHOTO_LOADING';
export const RANDOM_PHOTO_SUCCESS = 'RANDOM_PHOTO_SUCCESS';
export const RANDOM_PHOTO_FAILED = 'RANDOM_PHOTO_FAILED';

export const APPROVED_PHOTO_SAVE_SUCCESS = 'APPROVED_PHOTO_SAVE_SUCCESS';
export const APPROVED_PHOTO_SAVE_FAILED = 'APPROVED_PHOTO_SAVE_FAILED';

export const REJECTED_PHOTO_SAVE_SUCCESS = 'REJECTED_PHOTO_SAVE_SUCCESS';
export const REJECTED_PHOTO_SAVE_FAILED = 'REJECTED_PHOTO_SAVE_FAILED';
